# Generated by Django 3.0.6 on 2020-05-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='item',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teachercreate',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Teachercreate',
        ),
    ]
