# Generated by Django 3.0.6 on 2020-05-10 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_assignment_studentsolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gradeassignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
                ('total', models.FloatField()),
                ('sol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_assignment', to='classroom.Studentsolution')),
            ],
        ),
    ]
